required_version: =~ 3

environments:
  dev:
  prod:

resources:
  - name: site
    uses: static
    with:
      subDomain: certificates
      website: true
    platform:
      assets:
        dist: _site
